import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Deletes ALL existing entries
  await knex('cards').del();

  // Inserts seed entries
  await knex('cards').insert([
    // ===== Rareté 1 — Communes (25) =====
    {
      card_id: 'DOG-001',
      name: 'Labrador Retriever',
      serie: 'Gen 1',
      description: 'Le gentil géant du quartier, toujours partant pour une balle.',
      image_url: 'https://tcdog.local/cards/labrador.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-002',
      name: 'Golden Retriever',
      serie: 'Gen 1',
      description: 'Sourire permanent et patience infinie avec les enfants.',
      image_url: 'https://tcdog.local/cards/golden_retriever.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-003',
      name: 'Berger Allemand',
      serie: 'Gen 1',
      description: 'Loyal, intelligent et prêt à tout pour protéger sa meute.',
      image_url: 'https://tcdog.local/cards/berger_allemand.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-004',
      name: 'Bouledogue Français',
      serie: 'Gen 1',
      description: 'Robuste, calme et fidèle protecteur du foyer.',
      image_url: 'https://tcdog.local/cards/bouledogue_francais.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-005',
      name: 'Yorkshire Terrier',
      serie: 'Gen 1',
      description: 'Petit format, grand caractère et pelage soyeux.',
      image_url: 'https://tcdog.local/cards/yorkshire.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-006',
      name: 'Beagle',
      serie: 'Gen 1',
      description: 'Nez surpuissant et gourmandise à toute épreuve.',
      image_url: 'https://tcdog.local/cards/beagle.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-007',
      name: 'Cocker Spaniel Anglais',
      serie: 'Gen 1',
      description: 'Oreilles tombantes et joie de vivre communicative.',
      image_url: 'https://tcdog.local/cards/cocker_anglais.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-008',
      name: 'Jack Russell Terrier',
      serie: 'Gen 1',
      description: 'Petit format, énergie sans limites et esprit chasseur.',
      image_url: 'https://tcdog.local/cards/jack_russell.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-009',
      name: 'Teckel',
      serie: 'Gen 1',
      description: 'Corps allongé, pattes courtes et flair de champion.',
      image_url: 'https://tcdog.local/cards/teckel.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-010',
      name: 'Boxer',
      serie: 'Gen 1',
      description: 'Bondissant, joueur et fidèle compagnon de famille.',
      image_url: 'https://tcdog.local/cards/boxer.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-011',
      name: 'Caniche',
      serie: 'Gen 1',
      description: 'Élégant, hypoallergénique et redoutablement intelligent.',
      image_url: 'https://tcdog.local/cards/caniche.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-012',
      name: 'Chihuahua',
      serie: 'Gen 1',
      description: "Petit mais débordant d'une énergie survoltée.",
      image_url: 'https://tcdog.local/cards/chihuahua.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-013',
      name: 'Staffordshire Bull Terrier',
      serie: 'Gen 1',
      description: 'Muscles apparents et cœur tendre pour toute la famille.',
      image_url: 'https://tcdog.local/cards/staffie.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-014',
      name: 'Shih Tzu',
      serie: 'Gen 1',
      description: 'Poil long, allure royale et tempérament de compagnie.',
      image_url: 'https://tcdog.local/cards/shih_tzu.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-015',
      name: 'Border Collie',
      serie: 'Gen 1',
      description: 'Le cerveau du troupeau, infatigable et hyper obéissant.',
      image_url: 'https://tcdog.local/cards/border_collie.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-016',
      name: 'Rottweiler',
      serie: 'Gen 1',
      description: 'Carrure imposante et dévouement sans faille.',
      image_url: 'https://tcdog.local/cards/rottweiler.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-017',
      name: 'Dalmatien',
      serie: 'Gen 1',
      description: 'Taches uniques et endurance de coureur de fond.',
      image_url: 'https://tcdog.local/cards/dalmatien.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-018',
      name: 'Husky Sibérien',
      serie: 'Gen 1',
      description: 'Regard perçant et instinct de traîneau intact.',
      image_url: 'https://tcdog.local/cards/husky.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-019',
      name: 'Bichon Frisé',
      serie: 'Gen 1',
      description: 'Boule de coton toujours de bonne humeur.',
      image_url: 'https://tcdog.local/cards/bichon_frise.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-020',
      name: 'Cavalier King Charles',
      serie: 'Gen 1',
      description: 'Douceur royale et regard qui fait fondre tout le monde.',
      image_url: 'https://tcdog.local/cards/cavalier_king_charles.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-021',
      name: 'Maltais',
      serie: 'Gen 1',
      description: 'Pelage blanc immaculé et tempérament de pot de colle affectueux.',
      image_url: 'https://tcdog.local/cards/maltais.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-022',
      name: 'Bulldog Anglais',
      serie: 'Gen 1',
      description: 'Démarche chaloupée et ronflements légendaires.',
      image_url: 'https://tcdog.local/cards/bulldog_anglais.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-023',
      name: 'Cocker Américain',
      serie: 'Gen 1',
      description: 'Yeux doux et oreilles interminables, star des salons.',
      image_url: 'https://tcdog.local/cards/cocker_americain.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-024',
      name: 'Berger des Shetland',
      serie: 'Gen 1',
      description: "Mini Colley au poil flamboyant et à l'instinct de berger.",
      image_url: 'https://tcdog.local/cards/sheltie.png',
      rarity: 1,
    },
    {
      card_id: 'DOG-025',
      name: 'Fox Terrier Poil Lisse',
      serie: 'Gen 1',
      description: "Vif, curieux et toujours à l'affût d'une bêtise.",
      image_url: 'https://tcdog.local/cards/fox_terrier.png',
      rarity: 1,
    },

    // ===== Rareté 2 — Peu communes (25) =====
    {
      card_id: 'DOG-026',
      name: 'Berger Australien',
      serie: 'Gen 1',
      description: 'Un meneur agile capable de guider toute son équipe.',
      image_url: 'https://tcdog.local/cards/berger_australien.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-027',
      name: 'Braque Allemand',
      serie: 'Gen 1',
      description: 'Chasseur polyvalent au nez infaillible.',
      image_url: 'https://tcdog.local/cards/braque_allemand.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-028',
      name: 'Setter Irlandais',
      serie: 'Gen 1',
      description: 'Robe rousse flamboyante et allure aristocratique.',
      image_url: 'https://tcdog.local/cards/setter_irlandais.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-029',
      name: 'Springer Spaniel Anglais',
      serie: 'Gen 1',
      description: 'Ressort sur pattes, increvable dans les fourrés.',
      image_url: 'https://tcdog.local/cards/springer_spaniel.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-030',
      name: 'Terre-Neuve',
      serie: 'Gen 1',
      description: 'Nageur émérite et sauveteur né.',
      image_url: 'https://tcdog.local/cards/terre_neuve.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-031',
      name: "Malamute d'Alaska",
      serie: 'Gen 1',
      description: 'Force tranquille taillée pour le grand froid.',
      image_url: 'https://tcdog.local/cards/malamute.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-032',
      name: 'Doberman',
      serie: 'Gen 1',
      description: 'Silhouette élancée et garde du corps redoutable.',
      image_url: 'https://tcdog.local/cards/doberman.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-033',
      name: 'Schnauzer Moyen',
      serie: 'Gen 1',
      description: 'Moustache impériale et vigilance constante.',
      image_url: 'https://tcdog.local/cards/schnauzer.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-034',
      name: 'West Highland White Terrier',
      serie: 'Gen 1',
      description: 'Blanc immaculé et tempérament haut en couleur.',
      image_url: 'https://tcdog.local/cards/westie.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-035',
      name: 'Bull Terrier',
      serie: 'Gen 1',
      description: "Tête en forme d'œuf et énergie de bulldozer joueur.",
      image_url: 'https://tcdog.local/cards/bull_terrier.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-036',
      name: 'Whippet',
      serie: 'Gen 1',
      description: 'Fusée de salon, sprinteur hors pair.',
      image_url: 'https://tcdog.local/cards/whippet.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-037',
      name: 'Basset Hound',
      serie: 'Gen 1',
      description: 'Oreilles qui traînent et flegme imperturbable.',
      image_url: 'https://tcdog.local/cards/basset_hound.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-038',
      name: 'Carlin',
      serie: 'Gen 1',
      description: 'Museau plissé et humour involontaire garanti.',
      image_url: 'https://tcdog.local/cards/carlin.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-039',
      name: 'Akita Inu',
      serie: 'Gen 1',
      description: 'Noblesse japonaise et loyauté légendaire.',
      image_url: 'https://tcdog.local/cards/akita_inu.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-040',
      name: 'Samoyède',
      serie: 'Gen 1',
      description: 'Sourire figé et pelage blanc éclatant.',
      image_url: 'https://tcdog.local/cards/samoyede.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-041',
      name: 'Dogue Allemand',
      serie: 'Gen 1',
      description: 'Géant débonnaire qui ignore sa propre taille.',
      image_url: 'https://tcdog.local/cards/dogue_allemand.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-042',
      name: 'Braque de Weimar',
      serie: 'Gen 1',
      description: "Robe grise argentée et regard d'ambre hypnotique.",
      image_url: 'https://tcdog.local/cards/braque_de_weimar.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-043',
      name: 'Épagneul Breton',
      serie: 'Gen 1',
      description: 'Petit chasseur increvable, toujours en mouvement.',
      image_url: 'https://tcdog.local/cards/epagneul_breton.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-044',
      name: 'Pointer Anglais',
      serie: 'Gen 1',
      description: 'Arrêt sur image parfait devant le gibier.',
      image_url: 'https://tcdog.local/cards/pointer_anglais.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-045',
      name: 'Berger Picard',
      serie: 'Gen 1',
      description: 'Poil hirsute et humour bien de chez nous.',
      image_url: 'https://tcdog.local/cards/berger_picard.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-046',
      name: 'Setter Anglais',
      serie: 'Gen 1',
      description: 'Robe mouchetée et démarche élégante.',
      image_url: 'https://tcdog.local/cards/setter_anglais.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-047',
      name: 'Terrier Écossais',
      serie: 'Gen 1',
      description: 'Silhouette carrée et détermination sans faille.',
      image_url: 'https://tcdog.local/cards/scottish_terrier.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-048',
      name: 'Chow Chow',
      serie: 'Gen 1',
      description: 'Lion miniature à la langue bleue mystérieuse.',
      image_url: 'https://tcdog.local/cards/chow_chow.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-049',
      name: 'Shar Peï',
      serie: 'Gen 1',
      description: 'Plis sur plis pour un look increvable de sagesse.',
      image_url: 'https://tcdog.local/cards/shar_pei.png',
      rarity: 2,
    },
    {
      card_id: 'DOG-050',
      name: 'Lhassa Apso',
      serie: 'Gen 1',
      description: 'Ancien gardien de monastère au poil impressionnant.',
      image_url: 'https://tcdog.local/cards/lhassa_apso.png',
      rarity: 2,
    },

    // ===== Rareté 3 — Rares (20) =====
    {
      card_id: 'DOG-051',
      name: 'Berger Belge Malinois',
      serie: 'Gen 1',
      description: "Athlète surdoué prisé des unités d'élite.",
      image_url: 'https://tcdog.local/cards/malinois.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-052',
      name: 'Shiba Inu Doré',
      serie: 'Gen 1',
      description: 'Une légende vivante au regard malicieux.',
      image_url: 'https://tcdog.local/cards/shiba_dore.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-053',
      name: 'Spitz Nain',
      serie: 'Gen 1',
      description: 'Format poche, personnalité de star.',
      image_url: 'https://tcdog.local/cards/poemranien.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-054',
      name: 'Bullmastiff',
      serie: 'Gen 1',
      description: 'Muraille silencieuse au cœur de guimauve.',
      image_url: 'https://tcdog.local/cards/bullmastiff.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-055',
      name: 'Dogue de Bordeaux',
      serie: 'Gen 1',
      description: 'Bave légendaire et force herculéenne.',
      image_url: 'https://tcdog.local/cards/dogue_de_bordeaux.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-056',
      name: 'Braque Hongrois Vizsla',
      serie: 'Gen 1',
      description: 'Robe fauve et énergie inépuisable de chasseur.',
      image_url: 'https://tcdog.local/cards/vizsla.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-057',
      name: 'Épagneul Papillon',
      serie: 'Gen 1',
      description: "Oreilles en forme d'ailes, esprit ultra vif.",
      image_url: 'https://tcdog.local/cards/papillon.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-058',
      name: 'Pinscher Nain',
      serie: 'Gen 1',
      description: 'Petit format, ego de grand chien.',
      image_url: 'https://tcdog.local/cards/pinscher_nain.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-059',
      name: 'Terrier du Tibet',
      serie: 'Gen 1',
      description: 'Porte-bonheur himalayen au poil fluide.',
      image_url: 'https://tcdog.local/cards/terrier_tibetain.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-060',
      name: 'Montagne des Pyrénées',
      serie: 'Gen 1',
      description: 'Gardien immaculé des troupeaux de montagne.',
      image_url: 'https://tcdog.local/cards/montagne_des_pyrenees.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-061',
      name: 'Berger de Beauce',
      serie: 'Gen 1',
      description: 'Silhouette noir et feu, autorité naturelle.',
      image_url: 'https://tcdog.local/cards/beauceron.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-062',
      name: 'Berger des Pyrénées',
      serie: 'Gen 1',
      description: 'Petite tornade rousse au flegme trompeur.',
      image_url: 'https://tcdog.local/cards/berger_des_pyrenees.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-063',
      name: 'Terrier Irlandais',
      serie: 'Gen 1',
      description: 'Robe rousse et tempérament de battant.',
      image_url: 'https://tcdog.local/cards/terrier_irlandais.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-064',
      name: 'Kerry Blue Terrier',
      serie: 'Gen 1',
      description: 'Pelage bleu-gris unique et fierté irlandaise.',
      image_url: 'https://tcdog.local/cards/kerry_blue_terrier.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-065',
      name: 'Cane Corso',
      serie: 'Gen 1',
      description: 'Mâchoire imposante et prestance de gladiateur.',
      image_url: 'https://tcdog.local/cards/cane_corso.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-066',
      name: 'Griffon Bruxellois',
      serie: 'Gen 1',
      description: 'Bouille humaine et caractère bien affirmé.',
      image_url: 'https://tcdog.local/cards/griffon_bruxellois.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-067',
      name: 'Basenji',
      serie: 'Gen 1',
      description: "Le chien qui n'aboie pas, mais qui yodle.",
      image_url: 'https://tcdog.local/cards/basenji.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-068',
      name: 'Lévrier Afghan',
      serie: 'Gen 1',
      description: 'Crinière soyeuse et allure de mannequin du désert.',
      image_url: 'https://tcdog.local/cards/levrier_afghan.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-069',
      name: 'Saluki',
      serie: 'Gen 1',
      description: 'Silhouette filiforme, vitesse de légende du désert.',
      image_url: 'https://tcdog.local/cards/saluki.png',
      rarity: 3,
    },
    {
      card_id: 'DOG-070',
      name: 'Komondor',
      serie: 'Gen 1',
      description: 'Pelage en cordes façon serpillière ambulante.',
      image_url: 'https://tcdog.local/cards/komondor.png',
      rarity: 3,
    },

    // ===== Rareté 4 — Très rares (20) =====
    {
      card_id: 'DOG-071',
      name: 'Xoloitzcuintle',
      serie: 'Gen 1',
      description: 'Peau nue millénaire et chaleur corporelle réputée.',
      image_url: 'https://tcdog.local/cards/xoloitzcuintle.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-072',
      name: 'Lévrier Écossais',
      serie: 'Gen 1',
      description: "Géant poilu à l'âme de gentleman des Highlands.",
      image_url: 'https://tcdog.local/cards/deerhound.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-073',
      name: 'Barzoï',
      serie: 'Gen 1',
      description: 'Élégance russe taillée pour la chasse au loup.',
      image_url: 'https://tcdog.local/cards/barzoi.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-074',
      name: 'Puli',
      serie: 'Gen 1',
      description: 'Dreadlocks naturelles et vivacité de berger hongrois.',
      image_url: 'https://tcdog.local/cards/puli.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-075',
      name: 'Bedlington Terrier',
      serie: 'Gen 1',
      description: 'Silhouette de mouton, tempérament de guerrier.',
      image_url: 'https://tcdog.local/cards/bedlington_terrier.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-076',
      name: 'Otterhound',
      serie: 'Gen 1',
      description: "L'une des races les plus rares du Royaume-Uni.",
      image_url: 'https://tcdog.local/cards/otterhound.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-077',
      name: 'Chien-loup Tchécoslovaque',
      serie: 'Gen 1',
      description: "Regard sauvage hérité d'un croisement avec le loup des Carpates.",
      image_url: 'https://tcdog.local/cards/chien_loup_tchecoslovaque.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-078',
      name: 'Azawakh',
      serie: 'Gen 1',
      description: 'Silhouette sculpturale née dans le Sahel.',
      image_url: 'https://tcdog.local/cards/azawakh.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-079',
      name: 'Sloughi',
      serie: 'Gen 1',
      description: 'Lévrier discret du Maghreb, chasseur silencieux.',
      image_url: 'https://tcdog.local/cards/sloughi.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-080',
      name: 'Chien Nu du Pérou',
      serie: 'Gen 1',
      description: 'Trésor national péruvien à la peau douce et nue.',
      image_url: 'https://tcdog.local/cards/chien_nu_perou.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-081',
      name: 'Lundehund Norvégien',
      serie: 'Gen 1',
      description: 'Six doigts par patte pour grimper les falaises à macareux.',
      image_url: 'https://tcdog.local/cards/lundehund.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-082',
      name: 'Thai Ridgeback',
      serie: 'Gen 1',
      description: 'Crête de poil à rebrousse-poil et instinct de survie affûté.',
      image_url: 'https://tcdog.local/cards/thai_ridgeback.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-083',
      name: 'Catalburun',
      serie: 'Gen 1',
      description: 'Truffe littéralement fendue en deux, rareté turque absolue.',
      image_url: 'https://tcdog.local/cards/catalburun.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-084',
      name: 'Bergamasque',
      serie: 'Gen 1',
      description: 'Pelage en nattes façon armure feutrée des Alpes.',
      image_url: 'https://tcdog.local/cards/bergamasco.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-085',
      name: "Chien d'Ours de Carélie",
      serie: 'Gen 1',
      description: 'Noir et blanc, aussi téméraire que face à un ours.',
      image_url: 'https://tcdog.local/cards/karelian_bear_dog.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-086',
      name: 'Chinook',
      serie: 'Gen 1',
      description: 'Race américaine rarissime née pour tracter les traîneaux.',
      image_url: 'https://tcdog.local/cards/chinook.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-087',
      name: 'Chien de Caroline',
      serie: 'Gen 1',
      description: 'Chien sauvage américain aux origines mystérieuses.',
      image_url: 'https://tcdog.local/cards/carolina_dog.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-088',
      name: 'Mudi',
      serie: 'Gen 1',
      description: 'Berger hongrois polyvalent, rare même en Hongrie.',
      image_url: 'https://tcdog.local/cards/mudi.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-089',
      name: 'Stabyhoun',
      serie: 'Gen 1',
      description: 'Perle frisonne au tempérament placide et rare.',
      image_url: 'https://tcdog.local/cards/stabyhoun.png',
      rarity: 4,
    },
    {
      card_id: 'DOG-090',
      name: 'Hamiltonstövare',
      serie: 'Gen 1',
      description: 'Chien courant suédois tricolore, discret et rare.',
      image_url: 'https://tcdog.local/cards/hamiltonstovare.png',
      rarity: 4,
    },

    // ===== Rareté 5 — Épiques (15) =====
    {
      card_id: 'DOG-091',
      name: 'Tosa Inu',
      serie: 'Gen 1',
      description: "Combattant silencieux entraîné à la manière d'un sumo.",
      image_url: 'https://tcdog.local/cards/tosa_inu.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-092',
      name: 'Kai Ken',
      serie: 'Gen 1',
      description: 'Robe tigrée rarissime venue des montagnes du Japon.',
      image_url: 'https://tcdog.local/cards/kai_ken.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-093',
      name: 'Kishu Ken',
      serie: 'Gen 1',
      description: 'Blanc pur et courage de chasseur de sanglier.',
      image_url: 'https://tcdog.local/cards/kishu_ken.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-094',
      name: 'Shikoku',
      serie: 'Gen 1',
      description: 'Loup miniature des forêts japonaises, quasi introuvable hors du Japon.',
      image_url: 'https://tcdog.local/cards/shikoku.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-095',
      name: 'Chien Chanteur de Nouvelle-Guinée',
      serie: 'Gen 1',
      description: "Hurlement unique digne d'une baleine à bosse.",
      image_url: 'https://tcdog.local/cards/new_guinea_singing_dog.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-096',
      name: 'Chien de Canaan',
      serie: 'Gen 1',
      description: "Race biblique redécouverte à l'état sauvage dans le désert du Néguev.",
      image_url: 'https://tcdog.local/cards/canaan_dog.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-097',
      name: 'Alopekis',
      serie: 'Gen 1',
      description: "Micro-race grecque antique, à peine quelques centaines d'individus.",
      image_url: 'https://tcdog.local/cards/alopekis.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-098',
      name: 'Cimarrón Uruguayo',
      serie: 'Gen 1',
      description: "Ancien chien féral d'Uruguay, symbole national indomptable.",
      image_url: 'https://tcdog.local/cards/cimarron_uruguayo.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-099',
      name: 'Presa Canario',
      serie: 'Gen 1',
      description: 'Force brute des Canaries dans un corps de colosse.',
      image_url: 'https://tcdog.local/cards/presa_canario.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-100',
      name: 'Dogo Argentino',
      serie: 'Gen 1',
      description: 'Blanc immaculé, créé pour chasser le puma en meute.',
      image_url: 'https://tcdog.local/cards/dogo_argentino.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-101',
      name: 'Petit Chien Lion',
      serie: 'Gen 1',
      description: "Coupe de lion et statut de l'une des races les plus rares au monde.",
      image_url: 'https://tcdog.local/cards/lowchen.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-102',
      name: 'Chien-loup de Saarloos',
      serie: 'Gen 1',
      description: 'Croisement néerlandais avec le loup, regard hypnotique.',
      image_url: 'https://tcdog.local/cards/saarloos.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-103',
      name: 'Drever',
      serie: 'Gen 1',
      description: 'Pattes courtes, nez suédois infaillible, quasi inconnu hors Scandinavie.',
      image_url: 'https://tcdog.local/cards/drever.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-104',
      name: 'Schillerstövare',
      serie: 'Gen 1',
      description: "Chien courant suédois d'une rareté extrême même en Suède.",
      image_url: 'https://tcdog.local/cards/schillerstovare.png',
      rarity: 5,
    },
    {
      card_id: 'DOG-105',
      name: 'Lagotto Romagnolo',
      serie: 'Gen 1',
      description: 'Boucles hypoallergéniques et flair hors normes pour la truffe.',
      image_url: 'https://tcdog.local/cards/lagotto_romagnolo.png',
      rarity: 5,
    },

    // ===== Rareté 6 — Légendaires (8) =====
    {
      card_id: 'DOG-106',
      name: 'Cerbère Mythique',
      serie: 'Gen 1',
      description: 'Le gardien suprême doté de trois têtes redoutables.',
      image_url: 'https://tcdog.local/cards/cerbere.png',
      rarity: 6,
    },
    {
      card_id: 'DOG-107',
      name: 'Fenrir des Glaces',
      serie: 'Gen 1',
      description: "Loup légendaire capable d'avaler le soleil, dit-on.",
      image_url: 'https://tcdog.local/cards/fenrir.png',
      rarity: 6,
    },
    {
      card_id: 'DOG-108',
      name: 'Anubis Doré',
      serie: 'Gen 1',
      description: "Chacal sacré, passeur des âmes de l'Égypte antique.",
      image_url: 'https://tcdog.local/cards/anubis.png',
      rarity: 6,
    },
    {
      card_id: 'DOG-109',
      name: 'Cadejo Nocturne',
      serie: 'Gen 1',
      description:
        "Chien fantomatique du folklore d'Amérique centrale, protecteur des voyageurs de nuit.",
      image_url: 'https://tcdog.local/cards/cadejo.png',
      rarity: 6,
    },
    {
      card_id: 'DOG-110',
      name: 'Black Shuck',
      serie: 'Gen 1',
      description: 'Spectre canin aux yeux de braise qui hante les côtes anglaises.',
      image_url: 'https://tcdog.local/cards/black_shuck.png',
      rarity: 6,
    },
    {
      card_id: 'DOG-111',
      name: 'Garmr le Gardien',
      serie: 'Gen 1',
      description: 'Molosse des Enfers nordiques, ne lâche jamais sa garde.',
      image_url: 'https://tcdog.local/cards/garmr.png',
      rarity: 6,
    },
    {
      card_id: 'DOG-112',
      name: 'Orthos Bicéphale',
      serie: 'Gen 1',
      description: "Frère de Cerbère, deux têtes valent mieux qu'une.",
      image_url: 'https://tcdog.local/cards/orthos.png',
      rarity: 6,
    },
    {
      card_id: 'DOG-113',
      name: 'Cù Sìth des Landes',
      serie: 'Gen 1',
      description:
        "Chien-fée vert des Highlands, son aboiement s'entend à trois collines de distance.",
      image_url: 'https://tcdog.local/cards/cu_sith.png',
      rarity: 6,
    },
  ]);
}
